FROM node:22-alpine
ARG DATABASE_URL

WORKDIR /app

COPY  . .
# COPY ./package ./package

# COPY ./package.json ./package.json
# COPY ./pnpm-lock.yaml ./pnpm-lock.yaml
# COPY ./pnpm-workspace.yaml ./pnpm-workspace.yaml
# COPY ./turbo.json ./turbo.json

RUN npm install -g pnpm
RUN pnpm install

# COPY ./apps/web ./apps/web

RUN DATABASE_URL=${DATABASE_URL} pnpm run build:web
RUN pnpm run db:generate

EXPOSE 3000

CMD [ "pnpm", "run", "start:web" ]