name: Frontend Deploy

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          build-args: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}
          context: .
          file: ./docker/Dockerfile.frontend
          push: true
          tags: devanshbhavsar/week27-frontend:${{ github.sha }}
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: 34.47.238.131
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: docker stop user_frontend && docker run --name user_frontend -d -p 3000:3000 100xdevs/week27-frontend:${{ github.sha }}
